### ISSUE TITLE
Error with new version of jQuery introduced by WP 4.5

### ISSUE THREAD

**Issue by damiarita** [anandkumar/jquery-smooth-scroll#4]
Hi WP just changed to a new version of jQuery.

There is a conflict with you JS. This is the error I get:

Uncaught Error: Syntax error, unrecognized expression: a[href*=#]:not([href=#]):not(.navtab):not(.carousel-control)
fa.error @ jquery.js?e441e8:2
fa.tokenize @ jquery.js?e441e8:2
fa.select @ jquery.js?e441e8:2
fa @ jquery.js?e441e8:2
n.fn.extend.find @ jquery.js?e441e8:2
jQuery.fn.find @ jquery-migrate.js?e441e8:642
n.fn.init @ jquery.js?e441e8:2
jQuery.fn.init @ jquery-migrate.js?e441e8:247
n @ jquery.js?e441e8:2
(anonymous function) @ jss-script.min.js?e441e8:1
i @ jquery.js?e441e8:2
j.fireWith @ jquery.js?e441e8:2
n.extend.ready @ jquery.js?e441e8:2
K @ jquery.js?e441e8:2

**Comment by anandkumar** [comment]
Hello @damiarita,

Are you sure? Because it's working fine for me and the demo sites which usages WordPress default theme and a custom theme.

Here are the links to demo:
http://demo.wpavenue.com/jquery-smooth-scroll-plugin/
http://demo.wpavenue.com/alice/2016/04/14/jquery-smooth-scroll-plugin-demo/

**Which theme and browser** you are using so I can try to replicate the problem!

Thanks

**Comment by damiarita** [comment]
Hi @anandkumar ,

Thank you for your answer.

You are absolutely right. I can't remember it now, but I saw the .php file of your plugin in my server and I had modified and disabled updates. I just reinstalled it and it works. I must have had an old version of the JS file.

I see you have both a .js and a .min.js versions of the script. I have to change the php to enqueue the minified version, and I everytime a new version of the plugin comes in, I will loose the modification.

What do you think about checking the constant: SCRIPT_DEBUG to decide whether the .js or the .min.js should be used?

Any other suggestion on a way of using the .min.js file without having to change you code?

Thnanks!

**Comment by anandkumar** [comment]
Hello,

I hope you have have a backup of the modified files. The best way to do such modification is to fork here on GitHub. It will keep track of all the changes you made. OR even creating a gist will be fine for small changes.

I think, I should come up with a panel so you (and others) could have option to retain the customizations. But If you are interested to do a few things yourself then you should probably fork this plugin or [watch the development](https://help.github.com/articles/watching-repositories/). Since it is a small plugin you could easily track the development.

PS: Closing the issue as there is no such bug. We may always have a disccussion on any of the support channel including https://twitter.com/geekyanand

**Comment by damiarita** [comment]
Great!

I created a pull request with the SCRIPT_DEBUG functionality for you to consider
